FROM ghcr.io/mysociety/data_common:sha-9e69303

# Make an empty project directory so the 'self' setup doesn't fail and scripts can be setup
# Override the .pth created at previous stages to point to where the working directory will land
COPY pyproject.toml poetry.loc[k] /setup/ 
COPY src/data_common/pyproject.toml src/data_common/poetry.loc[k] /setup/src/data_common/
RUN mkdir /setup/src/composite_uk_imd && touch /setup/src/composite_uk_imd/__init__.py \
    && touch /setup/src/data_common/__init__.py \
    && export PATH="$HOME/.poetry/bin:$PATH" \
    && cd /setup/ && poetry install \
    && echo "/workspaces/composite_uk_imd/src/" > /usr/local/lib/python3.10/site-packages/composite_uk_imd.pth \
    && echo "/workspaces/composite_uk_imd/src/data_common/src" > /usr/local/lib/python3.10/site-packages/data_common.pth
