#!/bin/bash 

echo "--------------"
echo "Running pytest"
echo "--------------"
pytest
pytestexit=$?
echo "--------------"
echo "Running black"
echo "--------------"
black . --check
blackexit=$?
echo "--------------"
echo "Running pyright"
echo "--------------"
pyright
pyrightexit=$?

echo "Pytest status: $pytestexit"
echo "Black status: $blackexit"
echo "Pyright status: $pyrightexit"

sum="$(($pytestexit + $blackexit + $pyrightexit))"

if [ "$sum" != "0" ]; then
    exit 1
else
    exit 0
fi