#!/bin/bash 

git remote rm template
git remote add template https://github.com/mysociety/template_data_repo
git fetch template
git merge template/main

cd src/data_common
git fetch origin
git pull origin main
git checkout main

cd ../..
cd docs/theme
git fetch origin
git pull origin main
git checkout main
