name: Build datasets and deploy

permissions:
  contents: write
  pages: write
  id-token: write

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
on:
  push: 
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo content
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          
      - name: Run tests and try and build project
        uses: mysociety/run-in-devcontainer@v1
        with:
          run: |
            pip install poetry
            script/test
            dataset build --all
            dataset version auto --auto-ban major --all --publish
            notebook render --publish --all
            
      - name: Push new data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update repo data based on source changes"

      - name: Setup Pages
        uses: actions/configure-pages@d875fa8dc18209f310fe6999f4cfbc96ee372c2b # v2.1.2

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: docs
          destination: docs/_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

      - uses: geekyeggo/delete-artifact@v1
        with:
          name: github-pages